---
- name: instalace VPN
  hosts: "{{ seznam_stanic }}"
  tasks:
  - name: instalace VPN z Chocolatey
    win_chocolatey: 
     name: openvpn
     state: present
  - name: kopírování přístupových certifikátů
    win_copy: 
     src: "{{ cesta_src }}"
     dest: "{{ cesta_dest }}"
     remote_src: yes
    vars: 
     ansible_become: yes
     ansible_become_method: runas
     ansible_become_user: "{{ superucet }}"
     ansible_become_pass: "{{ superheslo }}"
     ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only 
