---
- name: instalace VPN
  hosts: "{{ seznam_stanic }}"
  tasks:
  - name: kontrola instalace OpenVPN
    win_command: reg query "HKLM\SOFTWARE\OpenVPN"
    ignore_errors: yes
    register: result
    
  - name: instalace VPN z Chocolatey
    win_chocolatey: 
     name: openvpn
     state: present
    when: result is failed
    
  - name: kopírování přístupových certifikátů
    win_copy: 
     src: "{{ cesta_src }}"
     dest: "{{ cesta_dest }}"
     remote_src: yes
    vars: 
     ansible_become: yes
     ansible_become_method: runas
     ansible_become_user: "{{ superucet }}"
     ansible_become_pass: "{{ superheslo }}"
     ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only 
